/* ============================================================
   OpportunityHub — Constants
   Central source of truth for all static data and enumerations.
   ============================================================ */

export const NIGERIAN_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa',
  'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo',
  'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo', 'Jigawa',
  'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
  'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun',
  'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
];

export const EDUCATION_LEVELS = [
  { value: 'primary', label: 'Primary School' },
  { value: 'jss', label: 'Junior Secondary (JSS1-3)' },
  { value: 'sss', label: 'Senior Secondary (SS1-3)' },
  { value: 'undergraduate', label: 'Undergraduate' },
  { value: 'masters', label: 'Masters' },
  { value: 'phd', label: 'PhD' },
  { value: 'nysc', label: 'NYSC' },
  { value: 'graduate', label: 'Recent Graduate' },
];

export const FIELDS_OF_STUDY = [
  'Accounting',
  'Agriculture',
  'Architecture',
  'Biochemistry',
  'Business Administration',
  'Chemical Engineering',
  'Civil Engineering',
  'Computer Science',
  'Economics',
  'Electrical Engineering',
  'English Language',
  'Environmental Science',
  'Fine Arts',
  'Law',
  'Mass Communication',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine & Surgery',
  'Microbiology',
  'Nursing',
  'Petroleum Engineering',
  'Pharmacy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Sociology',
];

export const OPPORTUNITY_TYPES = [
  'Scholarship',
  'Job',
  'Internship',
  'Grant',
  'Competition',
  'Fellowship',
];

export const NYSC_STATUSES = [
  'Prospective',
  'Serving',
  'Completed',
  'Exempted',
];

export const APPLICATION_STATUSES = [
  'Saved',
  'Preparing',
  'Applied',
  'Interviewing',
  'Accepted',
  'Rejected',
];

export const NIGERIAN_UNIVERSITIES = [
  'Ahmadu Bello University',
  'Bayero University Kano',
  'Covenant University',
  'Federal University of Technology Akure',
  'Federal University of Technology Minna',
  'Federal University of Technology Owerri',
  'Lagos State University',
  'Nnamdi Azikiwe University',
  'Obafemi Awolowo University',
  'University of Abuja',
  'University of Benin',
  'University of Calabar',
  'University of Ibadan',
  'University of Ilorin',
  'University of Jos',
  'University of Lagos',
  'University of Maiduguri',
  'University of Nigeria Nsukka',
  'University of Port Harcourt',
  'University of Uyo',
  'Babcock University',
  'Pan-Atlantic University',
  'American University of Nigeria',
  'Bowen University',
  'Lead City University',
  'Landmark University',
  'Afe Babalola University',
  'Federal University Oye-Ekiti',
  'Federal University Dutse',
  'Federal University Lafia',
  'Federal University Lokoja',
  'Yaba College of Technology',
  'Kaduna Polytechnic',
  'The Polytechnic Ibadan',
  'Federal Polytechnic Nekede',
];

export const NIGERIAN_SECONDARY_SCHOOLS = [
  "King's College, Lagos",
  "Queen's College, Lagos",
  'Federal Government College, Kano',
  'Federal Government College, Kaduna',
  'Federal Government College, Enugu',
  'Federal Government College, Ijanikin Lagos',
  'Federal Government College, Port Harcourt',
  'Federal Government College, Jos',
  'Federal Government College, Owerri',
  'Federal Government College, Warri',
  'Federal Government College, Odogbolu',
  'Federal Government College, Sokoto',
  'Federal Government College, Maiduguri',
  'Federal Government Girls College, Abaji',
  'Federal Government Girls College, Bwari Abuja',
  'Federal Government Girls College, Oyo',
  'Federal Government Girls College, Benin',
  'Federal Government Girls College, Calabar',
  'Loyola Jesuit College, Abuja',
  'Corona Secondary School, Agbara',
  'Atlantic Hall, Poka Epe',
  'Day Waterman College, Abeokuta',
  'Vivian Fowler Memorial College for Girls, Ikeja',
  'British International School, Victoria Island Lagos',
  'Greensprings School, Anthony & Lekki Lagos',
  'Dowen College, Lekki Lagos',
  'Grange School, Ikeja Lagos',
  'Christ The King College (CKC), Onitsha',
  'Dennis Memorial Grammar School (DMGS), Onitsha',
  'Government College, Ibadan',
  'Barewa College, Zaria',
  'Nigerian Military School (NMS), Zaria',
  'Air Force Military School, Jos',
  'Command Secondary School, Ipaja Lagos',
  'Command Secondary School, Kaduna',
  'St. Gregory’s College, Ikoyi Lagos',
  'Baptist High School, Port Harcourt',
  'St. Thomas Aquinas College, Akure',
  'International School Ibadan (ISI)',
  'University of Lagos International School (ISL)',
  'ABU Demonstration Secondary School, Zaria',
];

export const NIGERIAN_PRIMARY_SCHOOLS = [
  'Corona Primary School, Gbagada & Victoria Island',
  'Chrisland Primary School, Opebi & VGC',
  'Greensprings Primary School, Anthony & Lekki',
  'Grange Primary School, Ikeja',
  'Children’s International School (CIS), Lekki',
  'St. Saviour’s School, Ikoyi & Ebute Metta',
  'Meadow Hall School, Lekki',
  'University of Lagos Staff School, Akoka',
  'ABU Staff School, Samaru Zaria',
  'University of Ibadan Staff School',
  'Army Children Primary School, Ikeja Military Cantonment',
  'Model Primary School, Maitama Abuja',
  'L.E.A. Primary School, Wuse Zone 3 Abuja',
  'St. Mary’s Private Primary School, Lagos Island',
  'Grace Children School, Gbagada Lagos',
  'Maryland Convent Private School, Maryland',
  'Living Spring Primary School, Port Harcourt',
  'Tender Care Primary School, Kano',
  'Air Force Primary School, Ikeja & Kaduna',
  'Navy Primary School, Ojo Lagos',
];

export const INTEREST_TAGS = [
  'Technology',
  'Entrepreneurship',
  'Data Science',
  'Artificial Intelligence',
  'Healthcare',
  'Finance',
  'Education',
  'Creative Arts',
  'Agriculture',
  'Climate & Environment',
  'Social Impact',
  'Engineering',
  'Law & Policy',
  'Media & Communications',
  'Research',
  'Leadership',
  'Sports',
];

export const OPPORTUNITY_SOURCES = [
  'University Notice Board',
  'Government Portal',
  'Private Organization',
  'NGO / Non-Profit',
  'International Body',
  'Community',
];

export const DOCUMENT_TYPES = [
  'Resume / CV',
  'Cover Letter',
  'Transcript',
  'Certificate',
  'Recommendation Letter',
  'Personal Statement',
  'Portfolio',
  'Other',
];
